#!/usr/bin/env bash

# ***This script was made by Clay Gomera (Drake)***
# Contributor: kup1o<kup1o@pm.me>
#  - Description: A simple screenshot dmenu script
#  - Dependencies: scrot, dmenu, notify-send, shotgun, hacksaw

## CREATING SCREENSHOT FOLDER ##
mkdir -p "$HOME/pictures/screenshots"
cd "$HOME/pictures/screenshots" || exit 0

## CHOICES ##
cho1=" Entire screen"
cho2=" Entire screen with delay"
cho3="  Focused window"
cho4=" Select area"
cho5="🗒 Entire screen to clipboard"
chos="$cho1\n$cho2\n$cho3\n$cho4\n$cho5"

## DELAY OPTIONS ##
del1=" 3 sec delay"
del2=" 5 sec delay"
del3=" 10 sec delay"
dels="$del1\n$del2\n$del3"

## DELAY FUNCTION ##
delays() {
    del=$(echo -e "$dels" | rofi -dmenu -b -l 3 -i -p "Select: ");
        case $del in
            $del1)
                scrot -d 3 && notify-send "Screenshot saved";;
            $del2)
                scrot -d 5 && notify-send "Screenshot saved";;
            $del3)
                scrot -d 10 && notify-send  "Screenshot saved"
        esac
}

## ENTIRE SCREEN FUNCTION ##
screen() {
        scrot && notify-send "Screenshot saved"
}

## FOCUSED WINDOW FUNCTION
window() {
        scrot -u -b && notify-send "Screenshot saved."
}

## SELECTED AREA FUNCTION ##
area() {
        scrot -s && notify-send "Screenshot saved."
}

## SELECT AREA TO CLIPBOARD
clipboard() {
  selection=$(hacksaw -f "-i %i -g %g")
  shotgun $selection - | xclip -t 'image/png' -selection clipboard
}

## MAIN ACTION ##
choice=$(echo -e "$chos" | rofi -dmenu -b -l 5 -i -p "Select: ")
case $choice in
    $cho1)
        screen;;
    $cho2)
        delays;;
    $cho3)
        window;;
    $cho4)
        area;;
    $cho5)
        clipboard
esac
